python ErrorDataSimulator_AllRates.py --data 'UFRGS'
python FairInterMulti_AllErrorRates.py --data 'UFRGS'
python ModelEvaluator_Error.py --data 'UFRGS' --model 'group' --setting 'all'
python FairInterSingle_AllDegrees.py --data 'UFRGS' --setting 'SingleCC'
python FairInterSingle_AllDegrees.py --data 'UFRGS' --setting 'SingleCC+KAM-CAL'
python ModelThresholdOptimizer_AllDegrees.py --data 'UFRGS' --setting 'SingleCC'
python ModelThresholdOptimizer_AllDegrees.py --data 'UFRGS' --setting 'SingleCC+KAM-CAL'
python ModelEvaluator_AllDegrees.py --data 'UFRGS' --setting 'SingleCC'
python ModelEvaluator_AllDegrees.py --data 'UFRGS' --setting 'SingleCC+KAM-CAL'